git:
  submodules: false
language: generic
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          env: LOAD_INTO_KICAD=true
          before_install:
            - sudo add-apt-repository ppa:js-reynaud/kicad-4 -y
            - sudo apt-get update -q
            - sudo apt-get install kicad -y
        - os: osx
          env: LOAD_INTO_KICAD=false
script:
  - ./init
  - ./update
  - if $LOAD_INTO_KICAD; then PYTHONPATH=/usr/lib/python2.7/dist-packages python load_all.py; fi
